from d/ndjbdns-app

copy dnscache/dnscache.conf /ndjbdns/etc/ndjbdns/
copy dnscache/ip /ndjbdns/etc/ndjbdns/ip
copy dnscache/servers /ndjbdns/etc/ndjbdns/servers

copy dnscache/entrypoint.sh /ndjbdns/bin/entrypoint.sh
entrypoint ["/ndjbdns/bin/entrypoint.sh"]
cmd []

